### ISSUE TITLE
Delta: Plus and Minus are reversed

### ISSUE THREAD

**Issue by ninelore** [jeroenwtf/gnome-nightscout#2]
![grafik](https://github.com/user-attachments/assets/db93d575-f719-4579-9cac-f50807a51242)

Tested latest master on NixOS Unstable Gnome 47 on 2 different devices

**Comment by jeroenwtf** [comment]
Hi! You're completely right. I never use deltas, didn't realize 😅 Fixed in https://github.com/jeroenwtf/gnome-nightscout/commit/95ff7e682d06c3524a3ca5b82b308fe7f5e654b0 and submitted the update to the GNOME Extensions directory for approval. I will close this when you confirm it's fixed.

Thank you very much!

**Comment by ninelore** [comment]
Cool. Thanks very much for the quick fix as well as your work generally on this :)
